### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by supertoto29**
**Warning :** Before creating a pull request, make sure that it does not already exists in the [pull requests](../). Thank you.

## Description
Add a backup from the IMU tested during the multiple pool test. The data acquisition is working. Just the settings were problematic.

## How has this been tested ?
Tested on both subs

## Checklist
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings

### CODE REVIEW

**Comment by supertoto29** [comment]
@Kam0ss  Should we keep a archive of the previous IMU program?

**Review by Kam0ss — APPROVED** [review]
LGTM

**Comment by Kam0ss** [comment]
> @Kam0ss Should we keep a archive of the previous IMU program?

Maybe we could keep it in Teams ?

**Comment by supertoto29** [comment]
> > @Kam0ss Should we keep a archive of the previous IMU program?
> 
> Maybe we could keep it in Teams ?

Sounds good I will create a archive the master? @Kam0ss A archive branch would be the best to keep all the git, no?

**Pull request merged**
